apiVersion: v1
kind: Service
metadata:
  name: mysql #mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306 #port number of the pod viewed by ClusterIP.
      protocol: TCP
      targetPort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce #Mounted on only one pod and can be read and written from only one pod.
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql #mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1 #Number of pods
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate #All existing Pods die before a new Pod is created.
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        imagePullPolicy: Never
        name: mysql #mysql-pod
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage #Going to do volumeMounts named mysql-storage.
          mountPath: /var/lib/mysql #The path is this.
      volumes: #The volume setting is as follows.
      - name: mysql-storage
        persistentVolumeClaim: #Connect remotely to stories created by system administrators.
          claimName: mysql-pvc
