apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_ftps
        imagePullPolicy: Never
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          tcpSocket:
            port: 21

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: command-port
    port: 21
    protocol: TCP
    targetPort: 21
  - name: data-port
    port: 20
    targetPort: 20
    protocol: TCP
  - name: pasv-port1
    port: 20000
    targetPort: 20000
  - name: pasv-port2
    port: 20001
    targetPort: 20001
