apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin #phpmyadmin-services
  annotations: #Thanks to metalLB, both services can share the same IP.
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer #This ip is the same as nginx's loadbalancerIP.
  loadBalancerIP: MINI_IP #mini_ip(must be entered in uppercase)

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin #phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin
        imagePullPolicy: Never
        name: phpmyadmin #phpmyadmin-pod
        ports:
          - containerPort: 5000
