#setup.sh: kubectl apply -f ./srcs/metallb/metallb.yaml
apiVersion: v1
kind: ConfigMap #Configuration file to apply metallb in idle state
metadata:
  namespace: metallb-system #metallb is the only entrance that can be accessed from the outside.
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - MINI_IP-MINI_IP
#Setting the ip band that minikube can use.
#Private ip band in my MAC: 192.168.49.1 ~ 192.168.49.255
#Private ip band in 42seoul cluster MAC: 192.168.99.100-192.168.99.255
