apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf #telegraf-deployment
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf #telegraf-pod
          image: telegraf
          imagePullPolicy: Never
          volumeMounts:
            - name: docker-unix-socket
              mountPath: /var/run/docker.sock
          envFrom:
            - secretRef:
              name: influxdb-secret
      volumes:
        - name: docker-unix-socket
          hostPath: #The path of the node where the Pods are located is used as the volume.
            path: /var/run/docker.sock
            type: Socket #Connect to a socket to collect data from Docker.
#Since telegraf collects data from docker and stores the collected data in influxDB,
#you need to connect to docker through a socket.
