apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx  # name of deployment
  labels:
    app: nginx
spec:
#replicas: 1  # number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ft_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        livenessProbe:  # 만약 kubectl exec deploy/nginx -- pkill sshd 로 sshd 프로세스를 죽이면 컨테이너 재시작
          initialDelaySeconds: 20
          periodSeconds: 10
          tcpSocket:
            port: 80
