apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.unverse.tf/allow-shared-ip: shared
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306
