#setup.sh: kubectl apply -f ./srcs/phpmyadmin/phpmyadmin.yaml >> logs.txt
#Just create Service and Deployment.
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  annotations: #Thanks to metalLB, both services can share the same IP.
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer #This ip is the same as nginx's loadbalancerIP.
  loadBalancerIP: 192.168.99.100 #External ip accessible from outside.

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: ft_services-phpmyadmin #Changed from phpmyadmin:latest
        imagePullPolicy: Never
        name: phpmyadmin
        ports: #Added part. livenessprobe
          - containerPort: 5000
